author: "Magnus Henoch <henoch@dtek.chalmers.se>"
category: "admin"
summary: "Flexible filtering by server policy"
home: "https://github.com/JohnBrodie/mod_filter"
url: "git@github.com:JohnBrodie/mod_filter.git"
